language: node_js
node_js: stable

cache:
  directories:
    - node_modules

addons:
  apt:
    packages:
      - xvfb

# before_install:
#   - openssl aes-256-cbc -K $encrypted_830d3b21a25d_key -iv $encrypted_830d3b21a25d_iv
#     -in id_rsa.enc -out ~/.ssh/id_rsa -d
#   - chmod 600 ~/.ssh/id_rsa

install:
  - npm install

script:
  - npm run test

after_success:
  - npm run build
  - tar -jcvf fudi-toys.tar.bz2  /dist   # 打包并压缩代码
  - scp fudi-toys.tar.bz2 root@116.196.84.125:~/  # 复制到生产服务器上
  - ssh root@116.196.84.125 'mkdir -p fudi-toys && tar -jxvf fudi-toys.tar.bz2 -C fudi-toys'   # 解压
  # - ssh root@116.196.84.125 'cd indoor-server && pm2 startOrReload pm2.json'  # 重启pm2

branches:
  only:
    - master