language: node_js
node_js: stable
cache:
  directories:
  - node_modules
addons:
  apt:
    packages:
    - xvfb
  ssh_known_hosts: 116.196.84.125

before_install:
- openssl aes-256-cbc -K $encrypted_1ab686472695_key -iv $encrypted_1ab686472695_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 116.196.84.125\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
- npm install

script:
- npm run test

after_success:
- npm run build
- tar -jcvf fudi-toys.tar.bz2  /dist
- scp fudi-toys.tar.bz2 root@116.196.84.125:~/
- ssh root@116.196.84.125 'mkdir -p fudi-toys && tar -jxvf fudi-toys.tar.bz2 -C fudi-toys'
branches:
  only:
  - master
